### ISSUE TITLE
Fields on nested structs

### ISSUE THREAD

**Issue by abh** [BoRuDar/configuration-yaml-file#1]
With this struct:

```go
type Config struct {
	Kafka struct {
		CA   string `default:"/etc/kafka-ca/tls/ca.crt" file_json:"Kafka.CA" file_yml:"ca"`
		Cert string `default:"/etc/kafka/tls/user.crt" file_yml:"kafka_cert"`
		Key  string `default:"/etc/kafka/tls/key.crt"`
	} `file_yml:"kafka"`
}
```

and this configuration file:

```yaml
kafka:
  ca: "/tmp/foo"

kafka_cert: "/tmp/crt.pem"
```

I'd have expected `Kafka.CA` to be set (and `Kafka.Cert` not to be set really), but the reverse is true.
